app = 'fso-11-ancient-pond-4440'
primary_region = 'arn'

[env]
  PORT = "3000" # add this where PORT matches the internal_port below

[processes]
  app = "node app.js" # add this

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

    [[http_service.http_checks]]
        interval = "0"
        grace_period = "5s"
        method = "GET"
        path = "/health"
        protocol = "http"
        timeout = "2s"
        tls_skip_verify = false

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
