name: Periodic Health Check

on:
  # schedule:
  #   - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Health check
        uses: Jtalk/url-health-check-action@v4
        with:
          url: https://fso-11-ancient-pond-4440.fly.dev/health
          max-attempts: 3
          retry-delay: 30s
          retry-all: true